name: python-notebooks-use-cases
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.7
    - numpy
    - pandas
    - matplotlib
    - jupyterlab
    - ipywidgets
    - biopython
    - seaborn
    - nodejs
    - pip
    - pip:
        - bcbio-gff
